name: EC2 command
on:
  push:
    branches:
      - sherine
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH
      run: sudo apt-get install -y openssh-client
    - name: Run commands on EC2
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@13.233.227.88 << EOF
        pwd
        EOF
