name: EC2 command pull
on:
  workflow_run:
    workflows: ["CI/CD Pipeline test"]
    types: 
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOC_USERNAME }}
        password: ${{ secrets.DOC_PASS }}
    - name: Install SSH
      run: sudo apt-get install -y openssh-client
    - name: Run commands on EC2
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no ec2-user@13.233.227.88 << EOF
        sudo su
        docker pull ${{ secrets.DOC_USERNAME }}/test:finale
        docker run -d ${{ secrets.DOC_USERNAME }}/test:finale
        EOF
